version: '3.8'
services:
  bd:
    container_name: bd_postgres
    image: postgres:14.0
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5433:5432
    volumes:
      - ./data:/var/lib/postgresql/data